# Generated by Django 5.1 on 2024-09-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(
                blank="True", null="True", upload_to="", verbose_name="Превью"
            ),
        ),
    ]
