# Generated by Django 5.1 on 2024-08-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Наименование категории",
                        max_length=100,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "depiction",
                    models.TextField(
                        blank="True",
                        help_text="Описание категории",
                        null="True",
                        verbose_name="Описание",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Наименование продукта",
                        max_length=100,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "depiction",
                    models.TextField(
                        blank="True",
                        help_text="Описание продукта",
                        null="True",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank="True",
                        help_text="Изображение(превью) продукта",
                        null="True",
                        upload_to="catalog/image",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Категория продукта",
                        max_length=100,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "price_buy",
                    models.IntegerField(
                        help_text="Цена за покупку продукта",
                        verbose_name="Цена за покупку",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        help_text="Дата создания(записи в БД) продукта",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        blank="True",
                        help_text="Дата последнего изменения(записи в БД)продукта",
                        null="True",
                        verbose_name="Дата последнего изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Наименование",
                "verbose_name_plural": "Наименования",
                "ordering": ("name", "category", "price_buy"),
            },
        ),
    ]
