# Generated by Django 5.1 on 2024-08-21 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="date_creation",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="date_modification",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank="True",
                help_text="Категория продукта",
                null="True",
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
    ]
