# Generated by Django 5.1 on 2024-08-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_rename_date_creation_product_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateTimeField(
                blank="True",
                help_text="Дата производства продукта",
                null="True",
                verbose_name="Дата производства",
            ),
            preserve_default="True",
        ),
    ]
