# Generated by Django 5.1 on 2024-08-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_rename_date_creation_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name", "category", "price_buy"),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=models.ImageField(
                blank="True",
                help_text="Изображение(превью) продукта",
                null="True",
                upload_to="catalog/photo",
                verbose_name="Изображение",
            ),
        ),
    ]
