# Generated by Django 5.1 on 2024-08-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=models.ImageField(
                blank="True",
                help_text="Изображение(превью) продукта",
                null="True",
                upload_to="photo",
                verbose_name="Изображение",
            ),
        ),
    ]
