# Generated by Django 5.1 on 2024-08-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=models.ImageField(
                blank="True",
                help_text="Изображение(превью) продукта",
                null="True",
                upload_to="catalog/photo",
                verbose_name="Изображение",
            ),
        ),
    ]
