# Generated by Django 5.1 on 2024-09-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата создания(записи в БД) продукта",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата последнего изменения(записи в БД)продукта",
                null="True",
                verbose_name="Дата последнего изменения",
            ),
        ),
    ]
