# Generated by Django 5.1 on 2024-09-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        help_text="Номер версии продукта", verbose_name="Номер версии"
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        help_text="Наименование версии продукта",
                        max_length=100,
                        verbose_name="Наименование версии",
                    ),
                ),
                (
                    "version_active",
                    models.BooleanField(
                        default=False,
                        help_text="Активная версия продукта",
                        verbose_name="Активная версия",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank="True",
                        help_text="Продукт, к которому привязана версия",
                        null="True",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия продукта",
                "verbose_name_plural": "Версии продуктов",
                "ordering": ("version_name", "version_number"),
            },
        ),
    ]
